from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from datetime import date
from datetime import datetime
from decimal import Decimal
from typing import Mapping
from typing import Sequence
from typing import TypeAlias

JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | Mapping[str, "JsonValue"] | Sequence["JsonValue"]
JsonObject: TypeAlias = Mapping[str, JsonValue]
JsonArray: TypeAlias = Sequence[JsonValue]


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestScenarioRecord:
    """
    Typed persistence-boundary record for a curated backtest scenario.
    """

    scenario_id: str
    name: str
    workflow_name: str
    start_date: date
    end_date: date
    symbols: tuple[str, ...]
    benchmark_symbol: str
    initial_cash: Decimal
    provider_profile: str
    initial_positions: JsonArray = ()
    parameters: JsonObject = field(default_factory=dict)
    expected_outcomes: JsonArray = ()
    metadata: JsonObject = field(default_factory=dict)

    def __post_init__(
        self,
    ) -> None:
        _require_non_empty(self.scenario_id, "scenario_id")
        _require_non_empty(self.name, "name")
        _require_non_empty(self.workflow_name, "workflow_name")
        _require_non_empty(self.benchmark_symbol, "benchmark_symbol")
        _require_non_empty(self.provider_profile, "provider_profile")
        if self.start_date > self.end_date:
            raise ValueError("start_date must be on or before end_date.")
        if not self.symbols:
            raise ValueError("symbols cannot be empty.")
        for symbol in self.symbols:
            _require_non_empty(symbol, "symbol")
        if self.initial_cash < Decimal("0"):
            raise ValueError("initial_cash cannot be negative.")


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestRunRecord:
    """
    Typed persistence-boundary record for a completed or failed backtest run.
    """

    backtest_run_id: str
    scenario_id: str
    workflow_name: str
    status: str
    success: bool
    started_at: datetime
    completed_at: datetime
    metrics: JsonObject = field(default_factory=dict)
    metadata: JsonObject = field(default_factory=dict)

    def __post_init__(
        self,
    ) -> None:
        _require_non_empty(self.backtest_run_id, "backtest_run_id")
        _require_non_empty(self.scenario_id, "scenario_id")
        _require_non_empty(self.workflow_name, "workflow_name")
        _require_non_empty(self.status, "status")
        if self.completed_at < self.started_at:
            raise ValueError(
                "completed_at must be greater than or equal to started_at."
            )


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestStepRecord:
    """
    Curated per-step summary linked to an underlying workflow execution id.
    """

    step_id: str
    backtest_run_id: str
    step_index: int
    timestamp: datetime
    workflow_run_id: str
    success: bool
    node_output_keys: tuple[str, ...] = ()
    summary: JsonObject = field(default_factory=dict)

    def __post_init__(
        self,
    ) -> None:
        _require_non_empty(self.step_id, "step_id")
        _require_non_empty(self.backtest_run_id, "backtest_run_id")
        _require_non_negative(self.step_index, "step_index")
        _require_non_empty(self.workflow_run_id, "workflow_run_id")
        for node_key in self.node_output_keys:
            _require_non_empty(node_key, "node_output_key")


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestPortfolioSnapshotRecord:
    """
    Curated portfolio snapshot captured after a backtest step.
    """

    snapshot_id: str
    backtest_run_id: str
    step_id: str
    timestamp: datetime
    cash: Decimal
    equity: Decimal
    market_value: Decimal
    positions: JsonObject = field(default_factory=dict)
    metadata: JsonObject = field(default_factory=dict)

    def __post_init__(
        self,
    ) -> None:
        _require_non_empty(self.snapshot_id, "snapshot_id")
        _require_non_empty(self.backtest_run_id, "backtest_run_id")
        _require_non_empty(self.step_id, "step_id")


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestFillRecord:
    """
    Curated simulated fill generated by the analytical backtest ledger.
    """

    fill_id: str
    backtest_run_id: str
    step_id: str
    timestamp: datetime
    symbol: str
    side: str
    quantity: Decimal
    price: Decimal
    status: str
    reason: str | None = None
    realized_pnl: Decimal = Decimal("0")
    metadata: JsonObject = field(default_factory=dict)

    def __post_init__(
        self,
    ) -> None:
        _require_non_empty(self.fill_id, "fill_id")
        _require_non_empty(self.backtest_run_id, "backtest_run_id")
        _require_non_empty(self.step_id, "step_id")
        _require_non_empty(self.symbol, "symbol")
        _require_non_empty(self.side, "side")
        _require_non_empty(self.status, "status")
        if self.quantity < Decimal("0"):
            raise ValueError("quantity cannot be negative.")
        if self.price < Decimal("0"):
            raise ValueError("price cannot be negative.")


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestMetricRecord:
    """
    Queryable metric value for a backtest run.
    """

    metric_id: str
    backtest_run_id: str
    metric_name: str
    metric_value: Decimal
    recorded_at: datetime
    metadata: JsonObject = field(default_factory=dict)

    def __post_init__(
        self,
    ) -> None:
        _require_non_empty(self.metric_id, "metric_id")
        _require_non_empty(self.backtest_run_id, "backtest_run_id")
        _require_non_empty(self.metric_name, "metric_name")
        _require_timezone_aware(self.recorded_at, "recorded_at")


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestArtifactRecord:
    """
    Persisted curated report artifact for a backtest run.
    """

    artifact_id: str
    backtest_run_id: str
    artifact_format: str
    content: str
    mime_type: str
    generated_at: datetime
    metadata: JsonObject = field(default_factory=dict)

    def __post_init__(
        self,
    ) -> None:
        _require_non_empty(self.artifact_id, "artifact_id")
        _require_non_empty(self.backtest_run_id, "backtest_run_id")
        _require_non_empty(self.artifact_format, "artifact_format")
        _require_non_empty(self.content, "content")
        _require_non_empty(self.mime_type, "mime_type")
        _require_timezone_aware(self.generated_at, "generated_at")


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestPersistenceBundle:
    """
    Atomic curated backtest persistence payload.
    """

    scenario: BacktestScenarioRecord
    run: BacktestRunRecord
    steps: tuple[BacktestStepRecord, ...] = ()
    portfolio_snapshots: tuple[BacktestPortfolioSnapshotRecord, ...] = ()
    fills: tuple[BacktestFillRecord, ...] = ()
    metrics: tuple[BacktestMetricRecord, ...] = ()
    artifacts: tuple[BacktestArtifactRecord, ...] = ()


@dataclass(
    frozen=True,
    slots=True,
)
class BacktestPersistenceResult:
    """
    Typed result returned by backtest persistence adapters.
    """

    success: bool
    records_persisted: int = 0
    backtest_run_id: str | None = None
    error: str | None = None

    def __post_init__(
        self,
    ) -> None:
        _require_non_negative(self.records_persisted, "records_persisted")
        if self.success and self.error is not None:
            raise ValueError("successful persistence results cannot include an error.")
        if self.success:
            _require_non_empty(self.backtest_run_id, "backtest_run_id")
        if not self.success:
            _require_non_empty(self.error, "error")

    @classmethod
    def succeeded(
        cls,
        *,
        backtest_run_id: str,
        records_persisted: int = 1,
    ) -> BacktestPersistenceResult:
        return cls(
            success=True,
            records_persisted=records_persisted,
            backtest_run_id=backtest_run_id,
        )

    @classmethod
    def failed(
        cls,
        error: str,
    ) -> BacktestPersistenceResult:
        return cls(
            success=False,
            error=error,
        )


def _require_non_empty(
    value: str | None,
    field_name: str,
) -> None:
    if value is None or not value.strip():
        raise ValueError(f"{field_name} cannot be empty.")


def _require_non_negative(
    value: int,
    field_name: str,
) -> None:
    if value < 0:
        raise ValueError(f"{field_name} cannot be negative.")


def _require_timezone_aware(
    value: datetime,
    field_name: str,
) -> None:
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError(f"{field_name} must be timezone-aware.")
