from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import field_validator


class RagStructuredCitation(BaseModel):
    """One model-declared citation reference in a structured RAG answer."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    citation_id: str = Field(min_length=1)
    claim_summary: str = Field(min_length=1)

    @field_validator("citation_id", "claim_summary")
    @classmethod
    def _strip_non_empty(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("structured RAG citation fields cannot be empty.")
        return stripped


class RagStructuredAnswerQuality(BaseModel):
    """Model-declared quality metadata for a structured RAG answer."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    confidence_score: float = Field(ge=0.0, le=1.0)
    grounding_summary: str = Field(min_length=1)
    limitations: tuple[str, ...] = ()
    refusal_reason: str | None = None

    @field_validator("grounding_summary")
    @classmethod
    def _strip_grounding_summary(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("grounding_summary cannot be empty.")
        return stripped

    @field_validator("limitations", mode="before")
    @classmethod
    def _coerce_limitations(cls, value: object) -> tuple[str, ...]:
        if value is None:
            return ()
        if isinstance(value, str):
            stripped = value.strip()
            return (stripped,) if stripped else ()
        if not isinstance(value, (list, tuple)):
            raise TypeError("limitations must be a sequence of strings.")
        limitations: list[str] = []
        for item in value:
            if not isinstance(item, str):
                raise TypeError("limitations must contain only strings.")
            stripped = item.strip()
            if stripped:
                limitations.append(stripped)
        return tuple(limitations)

    @field_validator("refusal_reason")
    @classmethod
    def _strip_refusal_reason(cls, value: str | None) -> str | None:
        if value is None:
            return None
        stripped = value.strip()
        return stripped or None


class RagStructuredAnswer(BaseModel):
    """Schema-enforced RAG answer generated by the configured LLM provider."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    answer_text: str = Field(min_length=1)
    citations: tuple[RagStructuredCitation, ...] = ()
    quality: RagStructuredAnswerQuality

    @field_validator("answer_text")
    @classmethod
    def _strip_answer_text(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("answer_text cannot be empty.")
        return stripped
