from pathlib import Path
import subprocess

path = Path("docs/process/session-reconstitution.md")
text = path.read_text(encoding="utf-8")
marker = "#### Preserve a fresh verifier context across repair/recheck"
insert = r'''#### Preserve a fresh verifier context across repair/recheck

Some owning workflows require a repaired candidate to return to the **same** fresh verifier context after a semantic FAIL. A hosted-runner process lifetime is not the verifier-context lifetime. For ChatGPT-hosted GitHub Actions + Copilot CLI execution, preserve resumable session state deliberately rather than assuming a later runner can recover it globally.

Use this transport contract whenever the owning skill requires same-verifier continuation:

1. Set `COPILOT_HOME` to a verifier-lifecycle-specific job-local directory before starting Copilot. Start the verifier with a stable lifecycle name when supported; do not rely on an autogenerated title as durable identity.
2. After the first terminal verifier turn, identify the exact Copilot session ID from the local session state and require exactly one session to match the lifecycle. Record the session ID together with the exact source state, proposal identity, verifier-skill blob, and Actions run ID.
3. Archive the complete `COPILOT_HOME` needed for resume, compute a SHA-256 digest of that archive, and upload it as a GitHub Actions artifact with retention long enough for ordinary Polaris continuation. The artifact is transport state, not repository authority.
4. Before deleting the temporary verifier branch, update the ChatGPT Session Ledger with the session ID, artifact ID, archive digest, source/candidate identity, and the latest terminal verifier verdict. A run URL without resumable session state is insufficient when the owning skill requires the same verifier to recheck a repair.
5. For the repaired candidate, download exactly that artifact, verify its digest and manifest bindings, restore it to the same `COPILOT_HOME`, and invoke Copilot with `--resume=<SESSION-ID>` plus the bounded recheck prompt. Do **not** use `--continue` for this purpose: it may select another recent/global session and therefore cannot prove verifier identity.
6. After every resumed terminal turn, persist the refreshed `COPILOT_HOME` again and replace the ledger's active verifier-session recovery handle with the new artifact/session binding before transport cleanup.
7. If exact `--resume=<SESSION-ID>` fails before inference, classify that as transport failure rather than a semantic verdict. Follow the owning workflow's lost-context/replacement rule and any explicit-human-authorization requirement; never silently create a new challenger and never describe a replacement or reduced-independence substitute as the same verifier context.

This is ChatGPT execution-substrate policy only. It does not alter `$verify-ticket-decomposition`, `$verify-spec-closure`, or any other canonical workflow's semantic independence rules.

'''
anchor = "For a normal ChatGPT-hosted `$verify-spec`, the operational target is **roughly 5–10 minutes under normal GitHub queue and Copilot availability**."
if marker not in text:
    if anchor not in text:
        raise SystemExit("required insertion anchor not found")
    text = text.replace(anchor, insert + anchor, 1)
    path.write_text(text, encoding="utf-8")
else:
    if insert.strip() not in text:
        raise SystemExit("continuation marker exists with unexpected content")

subprocess.run(["git", "diff", "--check"], check=True)
subprocess.run(["git", "config", "user.name", "Bob Taylor"], check=True)
subprocess.run(["git", "config", "user.email", "bobltaylorjr@gmail.com"], check=True)
subprocess.run(["git", "add", str(path)], check=True)
changed = subprocess.check_output(["git", "diff", "--cached", "--name-only"], text=True).splitlines()
if not changed:
    raise SystemExit(0)
if changed != [str(path)]:
    raise SystemExit(f"unexpected changed paths: {changed}")
subprocess.run(["git", "commit", "-m", "docs(process): preserve fresh verifier session continuity"], check=True)
subprocess.run(["git", "push", "origin", "HEAD:main"], check=True)
